networks:
  pantos-validator-node:
    name: pantos-validator-node-${STACK_IDENTIFIER}-${INSTANCE-1}
    driver: overlay
    internal: true
    attachable: true
  pantos-validator-node-primary:
    name: pantos-validator-node-${STACK_IDENTIFIER}-primary
    driver: overlay
    attachable: true

services:
  app:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    image: ${DOCKER_REGISTRY-pantosio}/validator-node-app:${DOCKER_TAG-local}
    build:
      context: .
      dockerfile: Dockerfile
      target: validatornode01
      x-bake:
        tags:
          - ${DOCKER_REGISTRY-pantosio}/validator-node-app:${DOCKER_TAG-local}
          - ${DOCKER_REGISTRY-pantosio}/validator-node-app:${EXTRA_TAG-local}
    networks:
      pantos-validator-node:
      pantos-validator-node-primary:
        aliases:
          - pantos-validator-node-${INSTANCE-1}
    env_file: []
    environment:
      # Ignore the env file inside the docker container
      PANTOS_ENV_FILE: ' '
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      APP_MODE: ${APP_MODE-primary}
      APP_LOG_FILE_ENABLED: 'false'
      APP_LOG_FORMAT: human_readable
      DB_URL: postgresql://pantos-validator-node:pantos@db/pantos-validator-node
      CELERY_BROKER: amqp://pantos-validator-node:pantos@broker:5672/pantos-validator-node
      CELERY_BACKEND: db+postgresql://pantos-validator-node:pantos@db/pantos-validator-node-celery
    ports:
      - 809${INSTANCE-0}:8080
    healthcheck:
      test: ["CMD", "/usr/bin/pantos-validator-node-server", "--status"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
  worker:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    image: ${DOCKER_REGISTRY-pantosio}/validator-node-worker:${DOCKER_TAG-local}
    build:
      context: .
      dockerfile: Dockerfile
      target: validatornode01-celery-worker
      x-bake:
        tags:
          - ${DOCKER_REGISTRY-pantosio}/validator-node-worker:${DOCKER_TAG-local}
          - ${DOCKER_REGISTRY-pantosio}/validator-node-worker:${EXTRA_TAG-local}
    networks:
      pantos-validator-node:
    env_file: []
    environment:
      # Ignore the env file inside the docker container
      PANTOS_ENV_FILE: ' '
      PANTOS_CELERY_AUTORESTART: 'true'
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      APP_MODE: ${APP_MODE-primary}
      CELERY_LOG_FORMAT: human_readable
      CELERY_LOG_FILE_ENABLED: 'false'
      DB_URL: postgresql://pantos-validator-node:pantos@db/pantos-validator-node
      CELERY_BROKER: amqp://pantos-validator-node:pantos@broker:5672/pantos-validator-node
      CELERY_BACKEND: db+postgresql://pantos-validator-node:pantos@db/pantos-validator-node-celery
    healthcheck:
      test: ["CMD", "/usr/bin/pantos-validator-node-celery", "--status"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      app:
        condition: service_healthy
  db:
    image: postgres:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      pantos-validator-node:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresql_data:/postgresql_data
      - type: bind
        source: ./db_init.sh
        target: /docker-entrypoint-initdb.d/init-user-db.sh
        read_only: true
  broker:
    image: rabbitmq:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    hostname: pantos-validator-node
    networks:
      pantos-validator-node:
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: pantos-validator-node
      RABBITMQ_DEFAULT_PASS: pantos
      RABBITMQ_DEFAULT_VHOST: pantos-validator-node
    volumes:
      - rabbitmq_data:/rabbitmq_data

volumes:
  postgresql_data:
  rabbitmq_data:
