#! /bin/bash

application_directory='/opt/pantos/validator-node'

# Run only if systemctl exists (doesn't in docker images)
if [ -x /bin/systemctl ]; then
    systemctl stop pantos-validator-node-celery
    systemctl stop pantos-validator-node-server
fi

rm --force ${application_directory}/wsgi.py
rm --recursive --force ${application_directory}/virtual-environment/
