"""drop_blockchain_id_check_constraint

Revision ID: 2b93b957d8a4
Revises: 578d480b68dc
Create Date: 2023-07-31 02:29:06.591960

"""
import alembic

# revision identifiers, used by Alembic.
revision = '2b93b957d8a4'
down_revision = '578d480b68dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.drop_constraint('transfers_check', 'transfers', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_check_constraint(
        'transfers_check', 'transfers',
        'source_blockchain_id <> destination_blockchain_id')
    # ### end Alembic commands ###
