"""Module that defines database-specific enumerations.

"""
import enum


class TransferStatus(enum.IntEnum):
    """Enumeration of possible transfer status values.

    """
    SOURCE_TRANSACTION_DETECTED = 0
    SOURCE_TRANSACTION_REVERTED = 1
    SOURCE_TRANSACTION_INVALID = 2
    DESTINATION_TRANSACTION_FAILED = 3
    DESTINATION_TRANSACTION_SUBMITTED = 4
    DESTINATION_TRANSACTION_CONFIRMED = 5
    SOURCE_REVERSAL_TRANSACTION_FAILED = 6
    SOURCE_REVERSAL_TRANSACTION_SUBMITTED = 7
    SOURCE_REVERSAL_TRANSACTION_CONFIRMED = 8
    SOURCE_TRANSACTION_DETECTED_NEW_NONCE_ASSIGNED = 100
    DESTINATION_TRANSACTION_FAILED_NEW_NONCE_ASSIGNED = 103
    SOURCE_REVERSAL_TRANSACTION_FAILED_NEW_NONCE_ASSIGNED = 106
